version: "3.1"
services:
  couchdb:
    image: "couchdb:latest"
    container_name: "couchdb"
    ports:
      - "5984:5984"
    networks:
      - default
      - traefik_default
    restart: "always"
    env_file:
      - "./.env"
    environment:
      COUCHDB_USER: "${COUCHDB_USER}"
      COUCHDB_PASSWORD: "${COUCHDB_PASSWORD}"
    volumes:
      - "./dbdata:/opt/couchdb/data"
      - "./dbconfig:/opt/couchdb/etc/local.d"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_default"
      - "traefik.http.services.couchdb.loadbalancer.server.port=5984"
      - "traefik.http.routers.couchdb.entrypoints=http"
      - "traefik.http.routers.couchdb.rule=Host(`couchdb.example.com`)"
      - "traefik.http.middlewares.couchdb-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.couchdb.middlewares=couchdb-https-redirect"
      - "traefik.http.routers.couchdb-secure.entrypoints=https"
      - "traefik.http.routers.couchdb-secure.rule=Host(`couchdb.example.com`)"
      - "traefik.http.routers.couchdb-secure.tls=true"
      - "traefik.http.routers.couchdb-secure.tls.certresolver=http"
      - "traefik.http.routers.couchdb-secure.service=couchdb"
      - "com.centurylinklabs.watchtower.enable=true"
  
networks:
  traefik_default:
    external: true