http:
  routers:
    base:
      rule: "Host(`example.com`)"
      service: base
      middlewares:
        - base-https-redirect
    base-secure:
      rule: "Host(`example.com`)"
      service: base
      tls:
        certResolver: http
    update:
      rule: "Host(`update.example.com`)"
      service: update
      middlewares:
        - update-https-redirect
    update-secure:
      rule: "Host(`update.example.com`)"
      service: update
      tls:
        certResolver: http

  services:
    base:
      loadBalancer:
        servers:
          - url: http://host.docker.internal:3000
    update:
      loadBalancer:
        servers:
          - url: http://host.docker.internal:8888

  middlewares:
    base-https-redirect:
      redirectScheme:
        scheme: https
    update-https-redirect:
      redirectScheme:
        scheme: https