api:
  dashboard: true

entryPoints:
  http:
    address: ":80"
  https:
    address: ":443"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  file:
    filename: routes.yml
    watch: true

certificatesResolvers:
  http:
    acme:
      email: example@example.com
      storage: "/acme/certs.json"
      httpChallenge:
        entryPoint: http
